Aws utils
MetOffice/PyPRECIS pull request #111
Opened 2022-03-04 14:28 UTC by zmaalick

2022-03-04 14:29 UTC, zmaalick commented
I relocate the aws scripts and create one utils.py 

methods to test: load_data and flush_data

2022-03-04 14:29 UTC, zmaalick commented
from utils import load_data, flush_data
data = load_data('s3://ias-pyprecis/data/future/*.nc')
print(data)

#flush_data()

2022-03-04 16:24 UTC, nhsavage requested changes
code works for me, but it wasn't immediately obbvious what the purpose of the code was or how it was expected to work. Can you please add a docstring to the newmodule explaining it's purpose and also to load data giving an example of how to use it (explaining that it returns a cubelist) and the same for flush_data explaining that it removes the local copy (while leaving the cubelist in memory)

Also - we might need to remove files other than netcdf so I don't think that the wildcard in flush_data should be *.nc see for example data/pp/cahpa/ which only has pp data


For real world use - do we need to be able to set the location of the data directory?

Finally, was the deletion of the sample.txt files intended?

2022-03-07 10:53 UTC, nhsavage approved these changes

2022-03-07 10:55 UTC, merged